include:
  files:
    - "**/*"

exclude: 
   files: 
     - ".git/**/*" 
     - ".vscode/**/*" 
     - "build/**/*" 
     - "dev/**/*" 
     - "**/__pycache__/**/*" 
     - "**/.eggs/**/*" 
     - "**/locales/**/*" 
     - "**/spec/**/*" 
     - "**/specs/**/*" 
     - "**/test/**/*" 
     - "**/tests/**/*" 
     - "**/mock/**/*" 
     - "**/mocks/**/*" 
     - "**/integration/**/*" 
     - "**/package-lock.json" 
     - "**/package.json" 
     - "**/npm-shrinkwrap.json" 
     - "**/node_modules/**/*" 
  keys:
    - ^foo
  values:
    - bar$

rules:
  starks:
    description: Values formatted like AWS Session Token
    message: AWS Session Token  # report will show this message
    severity: CRITICAL           # one of BLOCKER, CRITICAL, MAJOR, MINOR, INFO

    key:        # specify key format
      regex: (aws.?session.?token)?
      ignorecase: True   # case-insensitive matching

    value:      # specify value format
      regex: (?i)w5c\.rCC(.{0,10})?[0-9a-z]{10,30}
      ignorecase: False  # case-sensitive matching
      minlen: 270        # value is at least this long
      isBase64: True     # value is base64-encoded
      isAscii: False     # value is binary data when decoded
      isUri: False       # value is not formatted like a URI

    similar: 0.35