name: whispers
on:
  push:
    branches:
      - main
jobs:
  scan:
    name: whispers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Whispers
       run: sudo pip install whispers

      # Scan repo for secrets
      - name: Run scanner for the repository
        run: whispers ${{ github.workspace }}