name: Secrets Scanning

on:
  push:
    branches: [ main ]

jobs:

  scan:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Installs secret scanner on the runner
      - name: Install Whispers
        run: sudo pip install whispers

      # Scan repo for secrets
      - name: Run scanner for the repository
        run: whispers ${{ github.workspace }}